EXAMPLES = [
    {
        "question": "How many active accounts are there currently?",
        "sql": "SELECT COUNT(*) AS active_account_count\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1\nAND ACCOUNT_STATUS_ID = 1",
    },
    {
        "question": "How many accounts are in 0-30 DPD bucket?",
        "sql": "-- Interpreted as: accounts with DPD between 0 and 30 inclusive (current + bucket 1)\nSELECT COUNT(*) AS account_count,\n       SUM(TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding_amount\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1\nAND DPD >= 0\nAND DPD <= 30",
    },
    {
        "question": "How many accounts are in 30-60 DPD bucket?",
        "sql": "SELECT COUNT(*) AS account_count,\n       SUM(TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding_amount,\n       SUM(PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1\nAND DPD >= 30\nAND DPD <= 60",
    },
    {
        "question": "How many accounts are in 60-90 DPD bucket?",
        "sql": "SELECT COUNT(*) AS account_count,\n       SUM(TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding_amount,\n       SUM(PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1\nAND DPD >= 60\nAND DPD <= 90",
    },
    {
        "question": "How many accounts are in 90+ DPD bucket?",
        "sql": "SELECT COUNT(*) AS account_count,\n       SUM(TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding_amount,\n       SUM(PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1\nAND DPD >= 90",
    },
    {
        "question": "What is the average outstanding per account?",
        "sql": "SELECT ROUND(AVG(TOTAL_OUTSTANDING_AMOUNT), 2) AS avg_outstanding_per_account\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1",
    },
    {
        "question": "What is the highest outstanding amount?",
        "sql": "SELECT MAX(TOTAL_OUTSTANDING_AMOUNT) AS highest_outstanding_amount\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1",
    },
    {
        "question": "What is the lowest outstanding amount?",
        "sql": "SELECT MIN(TOTAL_OUTSTANDING_AMOUNT) AS lowest_outstanding_amount\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1",
    },
    {
        "question": "How many personal loan accounts do we have?",
        "sql": "-- Interpreted as: count of accounts where product name is 'Personal Loan'\n\nSELECT COUNT(*) AS personal_loan_account_count\nFROM CN_CORE.ACCOUNT a\nLEFT JOIN CN_CORE.PRODUCT_TYPE pt ON a.PRODUCT_CODE = pt.PRODUCT_CODE\nWHERE a.RECORD_STATUS = 1\nAND UPPER(pt.PRODUCT_NAME) LIKE '%PERSONAL LOAN%'",
    },
    {
        "question": "What is the total outstanding amount in the portfolio?",
        "sql": "SELECT SUM(TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding_amount\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1",
    },
    {
        "question": "Show collections by branch",
        "sql": "SELECT a.BRANCH_CODE,\n       COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts,\n       SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n       SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n       ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.COLLECTION_CASE cc\nLEFT JOIN CN_CORE.ACCOUNT a ON cc.ACCOUNT_ID = a.ID\nGROUP BY a.BRANCH_CODE\nORDER BY total_collected DESC",
    },
    {
        "question": "Show collections by region",
        "sql": '-- Interpreted as: "region" mapped to BRANCH_CODE from CN_CORE.ACCOUNT as no region column exists in schema\n\nSELECT a.BRANCH_CODE AS region,\n       COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts,\n       SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n       SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n       SUM(cc.TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding,\n       ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.COLLECTION_CASE cc\nLEFT JOIN CN_CORE.ACCOUNT a ON cc.ACCOUNT_ID = a.ID\nGROUP BY a.BRANCH_CODE\nORDER BY total_collected DESC',
    },
    {
        "question": "Show accounts grouped by DPD and product",
        "sql": "-- Interpreted as: DPD bucket distribution with account count and outstanding amount, grouped by product and DPD range\n\nSELECT pt.PRODUCT_NAME,\n       CASE\n           WHEN a.DPD = 0 THEN 'Current (0 DPD)'\n           WHEN a.DPD BETWEEN 1 AND 30 THEN '1-30 DPD'\n           WHEN a.DPD BETWEEN 31 AND 60 THEN '31-60 DPD'\n           WHEN a.DPD BETWEEN 61 AND 90 THEN '61-90 DPD'\n           WHEN a.DPD BETWEEN 91 AND 180 THEN '91-180 DPD'\n           WHEN a.DPD BETWEEN 181 AND 365 THEN '181-365 DPD'\n           WHEN a.DPD > 365 THEN '365+ DPD'\n       END AS dpd_bucket,\n       COUNT(a.ID) AS account_count,\n       SUM(a.TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding_amount,\n       SUM(a.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n       SUM(a.TOTAL_OVERDUE_AMOUNT) AS total_overdue_amount,\n       ROUND(AVG(a.DPD), 2) AS avg_dpd\nFROM CN_CORE.ACCOUNT a\nLEFT JOIN CN_CORE.PRODUCT_TYPE pt ON a.PRODUCT_CODE = pt.PRODUCT_CODE\nWHERE a.RECORD_STATUS = 1\nGROUP BY pt.PRODUCT_NAME,\n         CASE\n             WHEN a.DPD = 0 THEN 'Current (0 DPD)'\n             WHEN a.DPD BETWEEN 1 AND 30 THEN '1-30 DPD'\n             WHEN a.DPD BETWEEN 31 AND 60 THEN '31-60 DPD'\n             WHEN a.DPD BETWEEN 61 AND 90 THEN '61-90 DPD'\n             WHEN a.DPD BETWEEN 91 AND 180 THEN '91-180 DPD'\n             WHEN a.DPD BETWEEN 181 AND 365 THEN '181-365 DPD'\n             WHEN a.DPD > 365 THEN '365+ DPD'\n         END\nORDER BY pt.PRODUCT_NAME,\n         MIN(a.DPD)",
    },
    {
        "question": "Show bank-wise recovery performance",
        "sql": "SELECT a.LENDER_NAME,\n       COUNT(DISTINCT cc.ACCOUNT_ID) AS total_accounts,\n       SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n       SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n       ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.COLLECTION_CASE cc\nLEFT JOIN CN_CORE.ACCOUNT a ON cc.ACCOUNT_ID = a.ID\nGROUP BY a.LENDER_NAME\nORDER BY recovery_rate_pct DESC",
    },
    {
        "question": "Compare recovery above and below 5 lakh exposure",
        "sql": "-- Interpreted as: Comparing recovery performance for accounts with principal outstanding above vs below 5 lakh (500,000)\n\nSELECT\n    CASE\n        WHEN cc.PRINCIPAL_OUTSTANDING_AMOUNT >= 500000 THEN 'Above 5 Lakh'\n        ELSE 'Below 5 Lakh'\n    END AS exposure_band,\n    COUNT(DISTINCT cc.ACCOUNT_ID) AS total_accounts,\n    SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n    SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n    SUM(cc.TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding,\n    SUM(cc.TOTAL_OVERDUE_AMOUNT) AS total_overdue,\n    ROUND(\n        SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100,\n    2) AS recovery_rate_pct,\n    ROUND(AVG(cc.DPD), 2) AS avg_dpd\nFROM CN_CORE.COLLECTION_CASE cc\nGROUP BY\n    CASE\n        WHEN cc.PRINCIPAL_OUTSTANDING_AMOUNT >= 500000 THEN 'Above 5 Lakh'\n        ELSE 'Below 5 Lakh'\n    END\nORDER BY\n    MIN(cc.PRINCIPAL_OUTSTANDING_AMOUNT) DESC",
    },
    {
        "question": "Which segment contributes most to defaults?",
        "sql": "SELECT pt.PRODUCT_NAME,\n       COUNT(a.ID) AS total_accounts,\n       SUM(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 ELSE 0 END) AS npa_accounts,\n       SUM(CASE WHEN a.NPA_FLAG = 'Y' THEN a.TOTAL_OUTSTANDING_AMOUNT ELSE 0 END) AS npa_outstanding,\n       ROUND(SUM(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 ELSE 0 END) / NULLIF(COUNT(a.ID), 0) * 100, 2) AS npa_rate_pct,\n       ROUND(SUM(CASE WHEN a.NPA_FLAG = 'Y' THEN a.TOTAL_OUTSTANDING_AMOUNT ELSE 0 END) / NULLIF(SUM(a.TOTAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS npa_outstanding_pct\nFROM CN_CORE.ACCOUNT a\nLEFT JOIN CN_CORE.PRODUCT_TYPE pt ON a.PRODUCT_CODE = pt.PRODUCT_CODE\nWHERE a.RECORD_STATUS = 1\nGROUP BY pt.PRODUCT_NAME\nORDER BY npa_accounts DESC",
    },
    {
        "question": "Identify accounts with no payments in last 90 days",
        "sql": "SELECT a.ACCOUNT_NUMBER,\n       a.LENDER_NAME,\n       a.BRANCH_CODE,\n       a.PRODUCT_CODE,\n       a.DPD,\n       a.TOTAL_OUTSTANDING_AMOUNT,\n       a.PRINCIPAL_OUTSTANDING_AMOUNT,\n       a.TOTAL_OVERDUE_AMOUNT,\n       a.LAST_PAYMENT_RECEIVED_DATE,\n       a.LAST_PAYMENT_RECEIVED_AMOUNT,\n       a.OVERDUE_SINCE_DATE,\n       a.NPA_FLAG\nFROM CN_CORE.ACCOUNT a\nWHERE a.RECORD_STATUS = 1\nAND (\n    a.LAST_PAYMENT_RECEIVED_DATE IS NULL\n    OR a.LAST_PAYMENT_RECEIVED_DATE < SYSDATE - 90\n)\nORDER BY a.TOTAL_OUTSTANDING_AMOUNT DESC\nFETCH FIRST 200 ROWS ONLY",
    },
    {
        "question": "What is the most surprising trend in the portfolio?",
        "sql": "SELECT\n    db.BUCKET_NAME,\n    db.DPD_START,\n    db.DPD_END,\n    COUNT(a.ID) AS TOTAL_ACCOUNTS,\n    ROUND(SUM(a.PRINCIPAL_OUTSTANDING_AMOUNT), 2) AS TOTAL_PRINCIPAL_OUTSTANDING,\n    ROUND(SUM(a.TOTAL_OVERDUE_AMOUNT), 2) AS TOTAL_OVERDUE,\n    ROUND(AVG(a.DPD), 2) AS AVG_DPD,\n    ROUND(SUM(a.TOTAL_PAID_AMOUNT), 2) AS TOTAL_PAID,\n    ROUND(SUM(a.WRITE_OFF_AMOUNT), 2) AS TOTAL_WRITE_OFF,\n    COUNT(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 END) AS NPA_COUNT,\n    COUNT(CASE WHEN a.SETTLEMENT_FLAG = 'Y' THEN 1 END) AS SETTLEMENT_COUNT,\n    COUNT(CASE WHEN a.RESTRUCTURED_FLAG = 'Y' THEN 1 END) AS RESTRUCTURED_COUNT,\n    ROUND(COUNT(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 END) * 100.0 / NULLIF(COUNT(a.ID), 0), 2) AS NPA_RATE_PCT,\n    ROUND(SUM(a.TOTAL_PAID_AMOUNT) / NULLIF(SUM(a.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS RECOVERY_RATE_PCT,\n    ROUND(AVG(a.MOB), 2) AS AVG_MOB,\n    ROUND(SUM(a.TOTAL_OVERDUE_AMOUNT) / NULLIF(SUM(a.TOTAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS OVERDUE_TO_OUTSTANDING_PCT,\n    COUNT(CASE WHEN a.ACTUAL_WRITE_OFF_FLAG = 'Y' THEN 1 END) AS WRITTEN_OFF_COUNT,\n    ROUND(AVG(a.INTEREST_RATE), 4) AS AVG_INTEREST_RATE,\n    ROUND(AVG(a.TOTAL_NO_OF_INSTALLMENT_OVERDUE), 2) AS AVG_INSTALLMENTS_OVERDUE,\n    ROUND(SUM(a.LAST_PAYMENT_RECEIVED_AMOUNT), 2) AS TOTAL_LAST_PAYMENTS_RECEIVED\nFROM CN_CORE.ACCOUNT a\nLEFT JOIN CN_CORE.DELINQUENCY_BUCKET db\n    ON a.DELINQUENCY_BUCKET_CODE = db.BUCKET_CODE\nWHERE a.RECORD_STATUS = 1\nGROUP BY\n    db.BUCKET_NAME,\n    db.DPD_START,\n    db.DPD_END,\n    db.BUCKET_NO\nORDER BY\n    db.BUCKET_NO ASC NULLS LAST\nFETCH FIRST 50 ROWS ONLY",
    },
    {
        "question": "What's the average outstanding?",
        "sql": "-- Interpreted as: Average total outstanding amount per account across active portfolio\n\nSELECT ROUND(AVG(TOTAL_OUTSTANDING_AMOUNT), 2) AS avg_outstanding_per_account,\n       ROUND(AVG(PRINCIPAL_OUTSTANDING_AMOUNT), 2) AS avg_principal_outstanding,\n       ROUND(AVG(INTEREST_OUTSTANDING_AMOUNT), 2) AS avg_interest_outstanding,\n       COUNT(*) AS total_accounts,\n       ROUND(SUM(TOTAL_OUTSTANDING_AMOUNT), 2) AS total_portfolio_outstanding\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1",
    },
    {
        "question": "Show top 10 agents by recovery",
        "sql": "-- Interpreted as: Top 10 ground-level collection agents (via CASE_TASK) by recovery rate, with collected amount and principal outstanding\n\nSELECT *\nFROM (\n    SELECT \n        u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n        u.USER_NAME,\n        u.DESIGNATION,\n        COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_handled,\n        SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n        SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n        ROUND(\n            SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2\n        ) AS recovery_rate_pct\n    FROM CN_CORE.CASE_TASK ct\n    LEFT JOIN CN_CORE.COLLECTION_CASE cc ON ct.COLLECTION_CASE_ID = cc.ID\n    LEFT JOIN UAMDB.USERS u ON ct.ALLOCATED_USER_ID = u.USER_ID\n    WHERE ct.USER_ALLOCATION_STATUS = 1\n    AND u.USER_STATUS = 'Active'\n    GROUP BY u.USER_ID, u.FIRST_NAME, u.LAST_NAME, u.USER_NAME, u.DESIGNATION\n    HAVING SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) > 0\n    ORDER BY recovery_rate_pct DESC\n)\nFETCH FIRST 10 ROWS ONLY",
    },
    {
        "question": "Remove agents with less than 50 accounts",
        "sql": "-- Interpreted as: Refine previous top 10 agents by recovery query, excluding agents handling fewer than 50 accounts\n\nSELECT *\nFROM (\n    SELECT \n        u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n        u.USER_NAME,\n        u.DESIGNATION,\n        COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_handled,\n        SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n        SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n        ROUND(\n            SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2\n        ) AS recovery_rate_pct\n    FROM CN_CORE.CASE_TASK ct\n    LEFT JOIN CN_CORE.COLLECTION_CASE cc ON ct.COLLECTION_CASE_ID = cc.ID\n    LEFT JOIN UAMDB.USERS u ON ct.ALLOCATED_USER_ID = u.USER_ID\n    WHERE ct.USER_ALLOCATION_STATUS = 1\n    AND u.USER_STATUS = 'Active'\n    GROUP BY u.USER_ID, u.FIRST_NAME, u.LAST_NAME, u.USER_NAME, u.DESIGNATION\n    HAVING COUNT(DISTINCT cc.ACCOUNT_ID) >= 50\n    AND SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) > 0\n    ORDER BY recovery_rate_pct DESC\n)\nFETCH FIRST 10 ROWS ONLY",
    },
    {
        "question": "Show accounts in 30-60 DPD",
        "sql": "-- Interpreted as: Show active accounts with DPD between 30 and 60, with key account details\n\nSELECT a.ACCOUNT_NUMBER,\n       a.LENDER_NAME,\n       a.BRANCH_CODE,\n       a.PRODUCT_CODE,\n       a.DPD,\n       a.PRINCIPAL_OUTSTANDING_AMOUNT,\n       a.INTEREST_OUTSTANDING_AMOUNT,\n       a.TOTAL_OUTSTANDING_AMOUNT,\n       a.TOTAL_OVERDUE_AMOUNT,\n       a.NPA_FLAG,\n       a.OVERDUE_SINCE_DATE,\n       a.LAST_PAYMENT_RECEIVED_DATE,\n       a.LAST_PAYMENT_RECEIVED_AMOUNT\nFROM CN_CORE.ACCOUNT a\nWHERE a.RECORD_STATUS = 1\nAND a.DPD >= 30\nAND a.DPD <= 60\nORDER BY a.DPD DESC, a.TOTAL_OUTSTANDING_AMOUNT DESC",
    },
    {
        "question": "Now exclude accounts that paid this week",
        "sql": "-- Interpreted as: Exclude accounts from 30-60 DPD list that had a payment received this week (within last 7 days from latest payment data)\n\nSELECT a.ACCOUNT_NUMBER,\n       a.LENDER_NAME,\n       a.BRANCH_CODE,\n       a.PRODUCT_CODE,\n       a.DPD,\n       a.PRINCIPAL_OUTSTANDING_AMOUNT,\n       a.INTEREST_OUTSTANDING_AMOUNT,\n       a.TOTAL_OUTSTANDING_AMOUNT,\n       a.TOTAL_OVERDUE_AMOUNT,\n       a.NPA_FLAG,\n       a.OVERDUE_SINCE_DATE,\n       a.LAST_PAYMENT_RECEIVED_DATE,\n       a.LAST_PAYMENT_RECEIVED_AMOUNT\nFROM CN_CORE.ACCOUNT a\nWHERE a.RECORD_STATUS = 1\nAND a.DPD >= 30\nAND a.DPD <= 60\nAND a.ID NOT IN (\n    SELECT DISTINCT pr.ACCOUNT_ID\n    FROM CN_CORE.PAYMENT_RECEIPT pr\n    WHERE pr.PAYMENT_TRANSACTION_DATE >= (\n        SELECT TRUNC(MAX(pr2.PAYMENT_TRANSACTION_DATE), 'IW')\n        FROM CN_CORE.PAYMENT_RECEIPT pr2\n    )\n    AND pr.PAYMENT_STATUS_CODE NOT IN ('BOUNCED', 'FAILED', 'REVERSED')\n    AND pr.ACCOUNT_ID IS NOT NULL\n)\nORDER BY a.DPD DESC, a.TOTAL_OUTSTANDING_AMOUNT DESC",
    },
    {
        "question": "What's left?",
        "sql": "-- Interpreted as: Continuing from Turn 5 context \u2014 show accounts in 30-60 DPD that have NOT yet paid this week (same filters as previous query), summarized as remaining count and outstanding amounts\n\nSELECT \n    COUNT(*) AS remaining_accounts,\n    ROUND(SUM(a.PRINCIPAL_OUTSTANDING_AMOUNT), 2) AS total_principal_outstanding,\n    ROUND(SUM(a.INTEREST_OUTSTANDING_AMOUNT), 2) AS total_interest_outstanding,\n    ROUND(SUM(a.TOTAL_OUTSTANDING_AMOUNT), 2) AS total_outstanding,\n    ROUND(SUM(a.TOTAL_OVERDUE_AMOUNT), 2) AS total_overdue,\n    ROUND(AVG(a.DPD), 2) AS avg_dpd,\n    COUNT(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 END) AS npa_accounts\nFROM CN_CORE.ACCOUNT a\nWHERE a.RECORD_STATUS = 1\nAND a.DPD >= 30\nAND a.DPD <= 60\nAND a.ID NOT IN (\n    SELECT DISTINCT pr.ACCOUNT_ID\n    FROM CN_CORE.PAYMENT_RECEIPT pr\n    WHERE pr.PAYMENT_TRANSACTION_DATE >= (\n        SELECT TRUNC(MAX(pr2.PAYMENT_TRANSACTION_DATE), 'IW')\n        FROM CN_CORE.PAYMENT_RECEIPT pr2\n    )\n    AND pr.PAYMENT_STATUS_CODE NOT IN ('BOUNCED', 'FAILED', 'REVERSED')\n    AND pr.ACCOUNT_ID IS NOT NULL\n)",
    },
    {
        "question": "How are we doing?",
        "sql": "-- Interpreted as: High-level portfolio health summary \u2014 key metrics across accounts, DPD, recovery, NPA, and collections\n\nSELECT\n    COUNT(a.ID)                                                                          AS total_accounts,\n    SUM(a.TOTAL_OUTSTANDING_AMOUNT)                                                      AS total_outstanding,\n    SUM(a.PRINCIPAL_OUTSTANDING_AMOUNT)                                                  AS total_principal_outstanding,\n    SUM(a.TOTAL_OVERDUE_AMOUNT)                                                          AS total_overdue,\n    ROUND(AVG(a.DPD), 2)                                                                 AS avg_dpd,\n    COUNT(CASE WHEN a.DPD = 0 THEN 1 END)                                                AS current_accounts,\n    COUNT(CASE WHEN a.DPD BETWEEN 1 AND 30 THEN 1 END)                                  AS dpd_1_30,\n    COUNT(CASE WHEN a.DPD BETWEEN 31 AND 60 THEN 1 END)                                 AS dpd_31_60,\n    COUNT(CASE WHEN a.DPD BETWEEN 61 AND 90 THEN 1 END)                                 AS dpd_61_90,\n    COUNT(CASE WHEN a.DPD > 90 THEN 1 END)                                              AS dpd_90_plus,\n    COUNT(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 END)                                        AS npa_accounts,\n    ROUND(COUNT(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 END) / NULLIF(COUNT(a.ID), 0) * 100, 2) AS npa_rate_pct,\n    COUNT(CASE WHEN a.ACTUAL_WRITE_OFF_FLAG = 'Y' THEN 1 END)                           AS written_off_accounts,\n    SUM(CASE WHEN a.ACTUAL_WRITE_OFF_FLAG = 'Y' THEN a.WRITE_OFF_AMOUNT ELSE 0 END)     AS total_write_off_amount,\n    SUM(cc.total_collected)                                                              AS total_collected,\n    ROUND(SUM(cc.total_collected) / NULLIF(SUM(a.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS overall_recovery_rate_pct\nFROM CN_CORE.ACCOUNT a\nLEFT JOIN (\n    SELECT\n        ACCOUNT_ID,\n        SUM(COLLECTED_AMOUNT) AS total_collected\n    FROM CN_CORE.COLLECTION_CASE\n    GROUP BY ACCOUNT_ID\n) cc ON a.ID = cc.ACCOUNT_ID\nWHERE a.RECORD_STATUS = 1",
    },
    {
        "question": "Show me bad accounts",
        "sql": "-- Interpreted as: accounts with DPD > 90 or NPA_FLAG = 'Y' (high risk / delinquent accounts)\nSELECT a.ACCOUNT_NUMBER,\n       a.LENDER_NAME,\n       a.PRODUCT_CODE,\n       a.BRANCH_CODE,\n       a.DPD,\n       a.NPA_FLAG,\n       a.TOTAL_OUTSTANDING_AMOUNT,\n       a.TOTAL_OVERDUE_AMOUNT,\n       a.PRINCIPAL_OUTSTANDING_AMOUNT,\n       a.OVERDUE_SINCE_DATE,\n       a.LAST_PAYMENT_RECEIVED_DATE,\n       a.ACTUAL_WRITE_OFF_FLAG,\n       a.SETTLEMENT_FLAG\nFROM CN_CORE.ACCOUNT a\nWHERE a.RECORD_STATUS = 1\n  AND (a.DPD > 90 OR a.NPA_FLAG = 'Y')\nORDER BY a.DPD DESC, a.TOTAL_OUTSTANDING_AMOUNT DESC\nFETCH FIRST 100 ROWS ONLY",
    },
    {
        "question": "Show high value accounts",
        "sql": "-- Interpreted as: accounts with high total outstanding amount (top 100 by outstanding)\nSELECT a.ACCOUNT_NUMBER,\n       a.LENDER_NAME,\n       a.BRANCH_CODE,\n       a.PRODUCT_CODE,\n       a.DPD,\n       a.LOAN_AMOUNT,\n       a.DISBURSED_AMOUNT,\n       a.PRINCIPAL_OUTSTANDING_AMOUNT,\n       a.INTEREST_OUTSTANDING_AMOUNT,\n       a.TOTAL_OUTSTANDING_AMOUNT,\n       a.TOTAL_OVERDUE_AMOUNT,\n       a.NPA_FLAG,\n       a.ACTUAL_WRITE_OFF_FLAG,\n       a.LAST_PAYMENT_RECEIVED_DATE,\n       a.LAST_PAYMENT_RECEIVED_AMOUNT\nFROM CN_CORE.ACCOUNT a\nWHERE a.RECORD_STATUS = 1\nORDER BY a.TOTAL_OUTSTANDING_AMOUNT DESC\nFETCH FIRST 100 ROWS ONLY",
    },
    {
        "question": "Show recovery this month vs last month till date",
        "sql": "-- Interpreted as: Compare total collected amount for current month vs same day-range of previous month (MTD vs prior MTD), using latest available data via subquery\n\nSELECT\n    report_period,\n    SUM(collected_amount) AS total_collected,\n    SUM(principal_outstanding) AS total_principal,\n    ROUND(SUM(collected_amount) / NULLIF(SUM(principal_outstanding), 0) * 100, 2) AS recovery_rate_pct,\n    COUNT(DISTINCT account_id) AS accounts\nFROM (\n    -- Current Month MTD\n    SELECT\n        'Current Month MTD' AS report_period,\n        cc.COLLECTED_AMOUNT AS collected_amount,\n        cc.PRINCIPAL_OUTSTANDING_AMOUNT AS principal_outstanding,\n        cc.ACCOUNT_ID\n    FROM CN_CORE.COLLECTION_CASE cc\n    WHERE cc.CASE_YEAR = (SELECT CASE_YEAR FROM (SELECT CASE_YEAR, CASE_MONTH, RANK() OVER (ORDER BY CASE_YEAR DESC, CASE_MONTH DESC) AS rnk FROM (SELECT DISTINCT CASE_YEAR, CASE_MONTH FROM CN_CORE.COLLECTION_CASE)) WHERE rnk = 1)\n      AND cc.CASE_MONTH = (SELECT CASE_MONTH FROM (SELECT CASE_YEAR, CASE_MONTH, RANK() OVER (ORDER BY CASE_YEAR DESC, CASE_MONTH DESC) AS rnk FROM (SELECT DISTINCT CASE_YEAR, CASE_MONTH FROM CN_CORE.COLLECTION_CASE)) WHERE rnk = 1)\n\n    UNION ALL\n\n    -- Previous Month same day range (MTD equivalent)\n    SELECT\n        'Last Month MTD' AS report_period,\n        cc.COLLECTED_AMOUNT AS collected_amount,\n        cc.PRINCIPAL_OUTSTANDING_AMOUNT AS principal_outstanding,\n        cc.ACCOUNT_ID\n    FROM CN_CORE.COLLECTION_CASE cc\n    WHERE cc.CASE_YEAR = (SELECT CASE_YEAR FROM (SELECT CASE_YEAR, CASE_MONTH, RANK() OVER (ORDER BY CASE_YEAR DESC, CASE_MONTH DESC) AS rnk FROM (SELECT DISTINCT CASE_YEAR, CASE_MONTH FROM CN_CORE.COLLECTION_CASE)) WHERE rnk = 2)\n      AND cc.CASE_MONTH = (SELECT CASE_MONTH FROM (SELECT CASE_YEAR, CASE_MONTH, RANK() OVER (ORDER BY CASE_YEAR DESC, CASE_MONTH DESC) AS rnk FROM (SELECT DISTINCT CASE_YEAR, CASE_MONTH FROM CN_CORE.COLLECTION_CASE)) WHERE rnk = 2)\n      AND EXTRACT(DAY FROM cc.CASE_START_DATE) <= (\n            SELECT MAX(EXTRACT(DAY FROM CASE_START_DATE))\n            FROM CN_CORE.COLLECTION_CASE\n            WHERE CASE_YEAR = (SELECT CASE_YEAR FROM (SELECT CASE_YEAR, CASE_MONTH, RANK() OVER (ORDER BY CASE_YEAR DESC, CASE_MONTH DESC) AS rnk FROM (SELECT DISTINCT CASE_YEAR, CASE_MONTH FROM CN_CORE.COLLECTION_CASE)) WHERE rnk = 1)\n              AND CASE_MONTH = (SELECT CASE_MONTH FROM (SELECT CASE_YEAR, CASE_MONTH, RANK() OVER (ORDER BY CASE_YEAR DESC, CASE_MONTH DESC) AS rnk FROM (SELECT DISTINCT CASE_YEAR, CASE_MONTH FROM CN_CORE.COLLECTION_CASE)) WHERE rnk = 1)\n      )\n)\nGROUP BY report_period\nORDER BY CASE report_period WHEN 'Current Month MTD' THEN 1 ELSE 2 END",
    },
    {
        "question": "Which agent collected most from accounts above 5 lakh in 90+ DPD?",
        "sql": "-- Interpreted as: Agent with highest total collected amount from accounts where PRINCIPAL_OUTSTANDING_AMOUNT >= 500000 AND DPD >= 90, using ground-level agents from CASE_TASK\n\nSELECT u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n       u.USER_NAME,\n       COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_handled,\n       SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n       SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n       ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.CASE_TASK ct\nLEFT JOIN UAMDB.USERS u ON ct.ALLOCATED_USER_ID = u.USER_ID\nLEFT JOIN CN_CORE.COLLECTION_CASE cc ON ct.COLLECTION_CASE_ID = cc.ID\nLEFT JOIN CN_CORE.ACCOUNT a ON cc.ACCOUNT_ID = a.ID\nWHERE a.RECORD_STATUS = 1\nAND a.DPD >= 90\nAND a.PRINCIPAL_OUTSTANDING_AMOUNT >= 500000\nAND ct.USER_ALLOCATION_STATUS = 1\nGROUP BY u.USER_ID, u.FIRST_NAME, u.LAST_NAME, u.USER_NAME\nORDER BY total_collected DESC\nFETCH FIRST 1 ROWS ONLY",
    },
    {
        "question": "Average recovery per agent vs median recovery per agent",
        "sql": "-- Interpreted as: Average collected amount per agent vs median collected amount per agent, using ALLOCATED_COLLECTION_USER_ID as the agent identifier\n\nSELECT\n    overall.agent_name,\n    overall.total_collected,\n    overall.accounts_handled,\n    overall.avg_recovery_per_account,\n    median_calc.median_recovery_per_account\nFROM (\n    SELECT\n        u.USER_ID,\n        u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n        SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n        COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_handled,\n        ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(COUNT(DISTINCT cc.ACCOUNT_ID), 0), 2) AS avg_recovery_per_account\n    FROM CN_CORE.COLLECTION_CASE cc\n    LEFT JOIN UAMDB.USERS u ON cc.ALLOCATED_COLLECTION_USER_ID = u.USER_ID\n    WHERE cc.ALLOCATED_COLLECTION_USER_ID IS NOT NULL\n    GROUP BY u.USER_ID, u.FIRST_NAME, u.LAST_NAME\n) overall\nLEFT JOIN (\n    SELECT\n        agent_user_id,\n        ROUND(MEDIAN(collected_per_account), 2) AS median_recovery_per_account\n    FROM (\n        SELECT\n            cc.ALLOCATED_COLLECTION_USER_ID AS agent_user_id,\n            cc.ACCOUNT_ID,\n            SUM(cc.COLLECTED_AMOUNT) AS collected_per_account\n        FROM CN_CORE.COLLECTION_CASE cc\n        WHERE cc.ALLOCATED_COLLECTION_USER_ID IS NOT NULL\n        GROUP BY cc.ALLOCATED_COLLECTION_USER_ID, cc.ACCOUNT_ID\n    )\n    GROUP BY agent_user_id\n) median_calc ON overall.USER_ID = median_calc.agent_user_id\nORDER BY overall.total_collected DESC",
    },
    {
        "question": "Which agent has highest efficiency recovery per account?",
        "sql": "-- Interpreted as: agent with highest average collected amount per unique account handled (efficiency = avg recovery per account)\n\nSELECT\n    u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n    u.USER_NAME,\n    u.DESIGNATION,\n    COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_handled,\n    SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n    SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n    ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(COUNT(DISTINCT cc.ACCOUNT_ID), 0), 2) AS avg_collected_per_account,\n    ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.COLLECTION_CASE cc\nLEFT JOIN UAMDB.USERS u ON cc.ALLOCATED_COLLECTION_USER_ID = u.USER_ID\nWHERE u.USER_ID IS NOT NULL\n  AND u.USER_STATUS = 'Active'\nGROUP BY\n    u.USER_ID,\n    u.FIRST_NAME,\n    u.LAST_NAME,\n    u.USER_NAME,\n    u.DESIGNATION\nHAVING COUNT(DISTINCT cc.ACCOUNT_ID) >= 10\nORDER BY avg_collected_per_account DESC\nFETCH FIRST 10 ROWS ONLY",
    },
    {
        "question": "Show top 5 agents excluding outliers",
        "sql": "-- Interpreted as: Top 5 agents by recovery rate, excluding outliers (agents with fewer than 10 accounts handled, to avoid skewed rates from small sample sizes)\n\nSELECT u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n       u.USER_NAME,\n       COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_handled,\n       SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n       SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal,\n       ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.COLLECTION_CASE cc\nLEFT JOIN UAMDB.USERS u ON cc.ALLOCATED_COLLECTION_USER_ID = u.USER_ID\nWHERE u.USER_STATUS = 'Active'\nGROUP BY u.FIRST_NAME, u.LAST_NAME, u.USER_NAME\nHAVING COUNT(DISTINCT cc.ACCOUNT_ID) >= 10\n   AND SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) > 0\n   AND ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) <= 100\nORDER BY recovery_rate_pct DESC\nFETCH FIRST 5 ROWS ONLY",
    },
    {
        "question": "Show reverse roll rate improvement",
        "sql": "-- Interpreted as: Roll-back (improvement) rate \u2014 accounts where RESOLUTION_STATUS = 'RB' (rolled back to a better bucket), grouped by month and delinquency bucket at case start\n\nSELECT\n    cc.CASE_YEAR,\n    cc.CASE_MONTH,\n    db_start.BUCKET_NAME                                          AS start_bucket,\n    db_curr.BUCKET_NAME                                           AS current_bucket,\n    COUNT(*)                                                      AS total_cases,\n    COUNT(CASE WHEN cc.RESOLUTION_STATUS = 'RB' THEN 1 END)       AS rolled_back_count,\n    COUNT(CASE WHEN cc.RESOLUTION_STATUS = 'RF' THEN 1 END)       AS rolled_forward_count,\n    ROUND(\n        COUNT(CASE WHEN cc.RESOLUTION_STATUS = 'RB' THEN 1 END)\n        / NULLIF(COUNT(*), 0) * 100, 2\n    )                                                             AS reverse_roll_rate_pct,\n    ROUND(\n        COUNT(CASE WHEN cc.RESOLUTION_STATUS = 'RF' THEN 1 END)\n        / NULLIF(COUNT(*), 0) * 100, 2\n    )                                                             AS forward_roll_rate_pct,\n    SUM(cc.COLLECTED_AMOUNT)                                      AS total_collected,\n    SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT)                          AS total_principal_outstanding,\n    ROUND(\n        SUM(cc.COLLECTED_AMOUNT)\n        / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2\n    )                                                             AS recovery_rate_pct\nFROM CN_CORE.COLLECTION_CASE cc\nLEFT JOIN CN_CORE.DELINQUENCY_BUCKET db_start\n    ON cc.CASE_START_DELINQUENCY_BUCKET_CODE = db_start.BUCKET_CODE\nLEFT JOIN CN_CORE.DELINQUENCY_BUCKET db_curr\n    ON cc.DELINQUENCY_BUCKET_CODE = db_curr.BUCKET_CODE\nWHERE (cc.CASE_YEAR * 100 + cc.CASE_MONTH) >=\n      (\n          SELECT MAX(CASE_YEAR * 100 + CASE_MONTH) - 5\n          FROM CN_CORE.COLLECTION_CASE\n      )\nGROUP BY\n    cc.CASE_YEAR,\n    cc.CASE_MONTH,\n    db_start.BUCKET_NAME,\n    db_curr.BUCKET_NAME,\n    db_start.BUCKET_NO,\n    db_curr.BUCKET_NO\nORDER BY\n    cc.CASE_YEAR,\n    cc.CASE_MONTH,\n    db_start.BUCKET_NO,\n    db_curr.BUCKET_NO",
    },
    {
        "question": "Show agents with no collections but many accounts",
        "sql": "-- Interpreted as: agents with active case allocations but zero total collected amount, ranked by number of accounts assigned\n\nSELECT \n    u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n    u.USER_NAME,\n    u.DESIGNATION,\n    COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_assigned,\n    SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n    SUM(cc.TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding,\n    SUM(cc.TOTAL_OVERDUE_AMOUNT) AS total_overdue,\n    ROUND(AVG(cc.DPD), 1) AS avg_dpd\nFROM CN_CORE.COLLECTION_CASE cc\nLEFT JOIN UAMDB.USERS u ON cc.ALLOCATED_COLLECTION_USER_ID = u.USER_ID\nWHERE cc.CASE_STATUS_ID = 1\n  AND u.USER_ID IS NOT NULL\n  AND u.USER_STATUS = 'Active'\nGROUP BY \n    u.USER_ID,\n    u.FIRST_NAME,\n    u.LAST_NAME,\n    u.USER_NAME,\n    u.DESIGNATION\nHAVING SUM(cc.COLLECTED_AMOUNT) = 0\n    OR SUM(cc.COLLECTED_AMOUNT) IS NULL\nORDER BY accounts_assigned DESC\nFETCH FIRST 50 ROWS ONLY",
    },
    {
        "question": "Compare secured vs unsecured loans",
        "sql": "-- Interpreted as: Compare portfolio metrics for secured vs unsecured loans based on SECURED_FLAG\n\nSELECT\n    CASE\n        WHEN a.SECURED_FLAG = 'Y' THEN 'Secured'\n        ELSE 'Unsecured'\n    END AS loan_type,\n    COUNT(a.ID) AS account_count,\n    SUM(a.LOAN_AMOUNT) AS total_sanctioned_amount,\n    SUM(a.DISBURSED_AMOUNT) AS total_disbursed_amount,\n    SUM(a.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal_outstanding,\n    SUM(a.TOTAL_OUTSTANDING_AMOUNT) AS total_outstanding_amount,\n    SUM(a.TOTAL_OVERDUE_AMOUNT) AS total_overdue_amount,\n    ROUND(AVG(a.DPD), 2) AS avg_dpd,\n    SUM(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 ELSE 0 END) AS npa_account_count,\n    ROUND(\n        SUM(CASE WHEN a.NPA_FLAG = 'Y' THEN 1 ELSE 0 END) /\n        NULLIF(COUNT(a.ID), 0) * 100, 2\n    ) AS npa_rate_pct,\n    ROUND(\n        SUM(a.TOTAL_OVERDUE_AMOUNT) /\n        NULLIF(SUM(a.TOTAL_OUTSTANDING_AMOUNT), 0) * 100, 2\n    ) AS overdue_rate_pct,\n    ROUND(AVG(a.INTEREST_RATE), 2) AS avg_interest_rate,\n    ROUND(AVG(a.TENURE), 2) AS avg_tenure_months,\n    ROUND(AVG(a.LOAN_AMOUNT), 2) AS avg_loan_amount\nFROM CN_CORE.ACCOUNT a\nWHERE a.RECORD_STATUS = 1\nGROUP BY\n    CASE\n        WHEN a.SECURED_FLAG = 'Y' THEN 'Secured'\n        ELSE 'Unsecured'\n    END\nORDER BY loan_type",
    },
    {
        "question": "Show top agent tie case",
        "sql": "-- Interpreted as: Show top agents by number of cases tied/allocated to them (active case task allocations)\n\nSELECT\n    u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n    u.USER_NAME,\n    u.DESIGNATION,\n    COUNT(DISTINCT ct.COLLECTION_CASE_ID) AS total_cases_allocated,\n    COUNT(DISTINCT cc.ACCOUNT_ID) AS total_accounts,\n    SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n    ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.CASE_TASK ct\nLEFT JOIN UAMDB.USERS u ON ct.ALLOCATED_USER_ID = u.USER_ID\nLEFT JOIN CN_CORE.COLLECTION_CASE cc ON ct.COLLECTION_CASE_ID = cc.ID\nWHERE ct.USER_ALLOCATION_STATUS = 1\n  AND u.USER_STATUS = 'Active'\nGROUP BY u.USER_ID, u.FIRST_NAME, u.LAST_NAME, u.USER_NAME, u.DESIGNATION\nORDER BY total_cases_allocated DESC\nFETCH FIRST 10 ROWS ONLY",
    },
    {
        "question": "Show average excluding null DPD",
        "sql": "-- Interpreted as: Average DPD of accounts where DPD is not NULL (RECORD_STATUS = 1 active accounts)\nSELECT \n    COUNT(*) AS account_count,\n    ROUND(AVG(DPD), 2) AS avg_dpd_excluding_null\nFROM CN_CORE.ACCOUNT\nWHERE RECORD_STATUS = 1\nAND DPD IS NOT NULL",
    },
    {
        "question": "Show count of distinct customers vs accounts",
        "sql": "-- Interpreted as: total distinct customers and total accounts in the portfolio\n\nSELECT\n    COUNT(DISTINCT a.CUSTOMER_ID) AS distinct_customer_count,\n    COUNT(a.ID) AS total_account_count,\n    ROUND(COUNT(a.ID) / NULLIF(COUNT(DISTINCT a.CUSTOMER_ID), 0), 2) AS avg_accounts_per_customer\nFROM CN_CORE.ACCOUNT a\nWHERE a.RECORD_STATUS = 1",
    },
    {
        "question": "Show top 5 agents",
        "sql": "-- Interpreted as: Top 5 agents by total collected amount (using ground-level agent from CASE_TASK)\n\nSELECT u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n       u.USER_NAME,\n       COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_handled,\n       SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n       SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal,\n       ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.CASE_TASK ct\nLEFT JOIN UAMDB.USERS u ON ct.ALLOCATED_USER_ID = u.USER_ID\nLEFT JOIN CN_CORE.COLLECTION_CASE cc ON ct.COLLECTION_CASE_ID = cc.ID\nWHERE ct.USER_ALLOCATION_STATUS = 1\nGROUP BY u.FIRST_NAME, u.LAST_NAME, u.USER_NAME\nORDER BY total_collected DESC\nFETCH FIRST 5 ROWS ONLY",
    },
    {
        "question": "Actually show bottom 5",
        "sql": "-- Interpreted as: Bottom 5 agents by recovery rate (lowest recovery rate, with at least some principal outstanding)\n\nSELECT u.FIRST_NAME || ' ' || u.LAST_NAME AS agent_name,\n       COUNT(DISTINCT cc.ACCOUNT_ID) AS accounts_handled,\n       SUM(cc.COLLECTED_AMOUNT) AS total_collected,\n       SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) AS total_principal,\n       ROUND(SUM(cc.COLLECTED_AMOUNT) / NULLIF(SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT), 0) * 100, 2) AS recovery_rate_pct\nFROM CN_CORE.COLLECTION_CASE cc\nLEFT JOIN UAMDB.USERS u ON cc.ALLOCATED_COLLECTION_USER_ID = u.USER_ID\nGROUP BY u.FIRST_NAME, u.LAST_NAME, u.USER_NAME\nHAVING SUM(cc.PRINCIPAL_OUTSTANDING_AMOUNT) > 0\nORDER BY recovery_rate_pct ASC\nFETCH FIRST 5 ROWS ONLY",
    },
]


def get_examples(query, n=4):
    q = query.lower()
    scored = []
    for ex in EXAMPLES:
        words = set(ex["question"].lower().split())
        score = len(words & set(q.split()))
        scored.append((score, id(ex), ex))
    top = [ex for s, _, ex in sorted(scored, reverse=True)[:n] if s > 0]
    if not top:
        top = EXAMPLES[:3]
    return chr(10).join(
        "User: " + ex["question"] + chr(10) + "SQL:" + chr(10) + ex["sql"] for ex in top
    )
